# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique thread identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the thread was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the thread was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional thread metadata"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this thread",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agui_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agui_thread",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique run identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current run status",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RunAgentInput data (messages, tools, state, etc.)",
                    ),
                ),
                (
                    "output_state",
                    models.JSONField(
                        blank=True,
                        help_text="Final state after run completion",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the run started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When the run finished", null=True
                    ),
                ),
                (
                    "parent_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent run for branching/time travel",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_runs",
                        to="django_agui.run",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Thread this run belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="django_agui.thread",
                    ),
                ),
            ],
            options={
                "db_table": "agui_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique message identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        help_text="Sender role (user, assistant, system, tool)",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content (text or base64 for binary)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("text", "Text"), ("binary", "Binary")],
                        default="text",
                        help_text="Content type (text or binary)",
                        max_length=20,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type for binary content (e.g., image/png, application/pdf)",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="File attachment (for binary content)",
                        null=True,
                        upload_to="agui/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for large files",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional message metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the message was created",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Run this message belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="django_agui.run",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Thread this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="django_agui.thread",
                    ),
                ),
            ],
            options={
                "db_table": "agui_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique tool call identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Name of the tool being called", max_length=200
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        blank=True, default=dict, help_text="Tool arguments"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Tool execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current tool call status",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the tool call started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When the tool call finished", null=True
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message containing this tool call",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_calls",
                        to="django_agui.message",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Run this tool call belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="django_agui.run",
                    ),
                ),
            ],
            options={
                "db_table": "agui_tool_call",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique event identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="AG-UI event type (e.g., TEXT_MESSAGE_START, TOOL_CALL_END)",
                        max_length=50,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Event data payload"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event was created",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Run this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="django_agui.run",
                    ),
                ),
            ],
            options={
                "db_table": "agui_event",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["user", "-updated_at"], name="agui_thread_user_id_73f1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["created_at"], name="agui_thread_created_1b0e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["thread", "-started_at"], name="agui_run_thread__f48d0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["status", "-started_at"], name="agui_run_status_f7ffae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["parent_run"], name="agui_run_parent__f40c86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created_at"], name="agui_messag_thread__4b62d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["run", "created_at"], name="agui_messag_run_id_c82791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["role", "created_at"], name="agui_messag_role_1e6fa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolcall",
            index=models.Index(
                fields=["run", "started_at"], name="agui_toolca_run_id_83e938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolcall",
            index=models.Index(
                fields=["status", "started_at"], name="agui_toolca_status_5c80ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["run", "created_at"], name="agui_event_run_id_f852e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="agui_event_event_t_a9024e_idx",
            ),
        ),
    ]
